sudo: false

language: java

jdk:
  - openjdk6
#  - openjdk7
#  - oraclejdk7
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uwolfer-github"
    token: $SONAR_TOKEN

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.sonar/cache/

after_success:
  if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then
    mvn clean cobertura:cobertura coveralls:report jacoco:prepare-agent test jacoco:report sonar:sonar;
  fi
